<?php
/**
 * @file
 * Hooks provided by ent_nodeblock module
 */

/**
 * Alter automatic block definition generated by ent_nodeblock in
 * the hook_block_info()
 * @param array $block : alterable block definition
 * @param object $node
 */
function hook_ent_nodeblock_info_alter(&$block, $node) {
  // change block title on the admin page
  $items = field_get_items('node', $node, 'field_ent_menu_user');
  $block['info'] = $node->title . " - " . $items[0]['value'];
}

/**
 * Alter automatic block generation in the hook_block_view()
 * @param $block
 * @param $node
 */
function hook_ent_nodeblock_view_alter(&$block, $node) {
  $block['title'] = 'my title';
  $block['content']['#theme_wrappers'] = array('ent_menu_wrapper');
}
