<?php
/**
 * @file
 * Hooks provided by ent_nodeblock module
 */

/**
 * Alter a block definition generated by ent_nodeblock in its hook_block_info()
 * @param array $block : alterable single block definition
 * @param object $node
 */
function hook_ent_nodeblock_info_alter(&$block, $node) {
  // change block title on the admin page
  $items = field_get_items('node', $node, 'field_ent_menu_user');
  $block['info'] = $node->title . " - " . $items[0]['value'];
}

/**
 * Alter automatic block generation in the hook_block_view()
 * ent_nodeblock use a renderable array for block content containing :
 * '#theme' => 'ent_nodeblock', // theme to render the node
 * '#node' => $node, // full node object
 * '#view_mode' => 'full', // view mode to render the node with ent_nodeblock theme
 * @param $block
 * @param $node
 */
function hook_ent_nodeblock_view_alter(&$block, $node) {
  $block['title'] = 'my title';
  $block['content']['#theme_wrappers'] = array('ent_menu_wrapper');
}
